### ISSUE TITLE
preceding-sexp is deprecated in emacs 25

### ISSUE THREAD

**Issue by vadali** [bbatsov/crux#35]
Hey, its not yet a bug, but you should probably [move away from preceding-sexp](https://github.com/bbatsov/crux/blob/master/crux.el#L316) for emacs 25.

    Warning (bytecomp): ‘preceding-sexp’ is an obsolete function (as of 25.1); use ‘elisp--preceding-sexp’ instead.

**Comment by bbatsov** [comment]
Any idea if `elisp--preceding-sexp` is available in older versions of Emacs?

**Comment by vadali** [comment]
I think only starting emacs 24.
However we could solve it using:
```lisp
(if (version< emacs-version "24")
      'preceding-sexp
    'elisp--preceding-sexp)
```

**Comment by bbatsov** [comment]
OK, thanks for checking this.
