### ISSUE TITLE
crux-cleanup-buffer-or-region doesn't operate on the entire buffer

### ISSUE THREAD

**Issue by danlamanna** [bbatsov/crux#7]
`crux-cleanup-buffer-or-region` operates on regions correctly, but it calls `untabify` only on the parts of the buffer after point.

I assume this has something to do with the `crux-with-region-or-buffer` macro, but I can't see where it's being used.

**Comment by goofansu** [comment]
According to [using-the-bundled-advices](https://github.com/bbatsov/crux/blob/bcbfdec127b71605c672a49f2d9d256a06b5e063/README.md#using-the-bundled-advices), you should add following lines in your config to do the trick:

```
(crux-with-region-or-buffer indent-region)
(crux-with-region-or-buffer untabify)
```
